version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Start Swarm Node
          command: sudo docker run --publish 8500:8500 --publish 8546:8546 --env DATADIR=/data --env PASSWORD=password123 --volume /tmp/swarm-data:/data --interactive --tty "ethdevops/swarm:v0.3.11" --nosync --maxpeers=0 --verbosity=4 --httpaddr=0.0.0.0 --nat=none --corsdomain=* --ws --wsaddr=0.0.0.0 --wsorigins=*
      - run:
          name: Setup
          command: yarn install && yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build and check
          command: yarn build && yarn lint
      - run:
          name: Project tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: '/tmp/test-reports/jest/results.xml'
      - store_test_results:
          path: /tmp/test-reports
